default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: rails_5
  username: user19
  password: 123456
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: rails__pro
  username: postgres
  password: postgres
  host: localhost